version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  
  # proxy:
  #   image: proxy:latest
  #   container_name: proxy
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.proxy.rule=Host(`proxy`)"
  #     - "traefik.http.services.proxy.loadbalancer.server.scheme=h2c"
  #   expose:
  #     - 50051
  #   hostname: proxy

  authservice:
    image: authservice:latest
    container_name: authservice
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authservice.rule=Host(`authservice`)"
      - "traefik.http.services.authservice.loadbalancer.server.scheme=h2c"
    expose:
      - 5000
    hostname: authservice
    depends_on: 
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    hostname: redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis.rule=Host(`redis`)"